name: Check

on: 
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Tests
        run: make

  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        example: [mock-injection, wiring-blink]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      -
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      -
        name: Install PlatformIO Core
        run: pip install --upgrade platformio
      -
        name: Build example
        run: pio test -d examples/wiring-blink/
      -
        name: Build Tests
        run: pio test