name: Check

on: 
  push: 
    branches:
      - main
      - master
  pull_request: 
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check CMake version
        run: cmake --version

      - name: Configure (CMake)
        run: cmake ${{ github.workspace }} -B${{ github.workspace }}/build

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test
        run: ctest --test-dir ${{ github.workspace }}/build --output-on-failure

  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        example: [mock-injection, wiring-blink]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Tests
        run: pio test -d examples/${{ matrix.example }}/
