name: Check

on: 
  push: 
    branches:
      - main
      - master
      - cmake-fetch
  pull_request: 
    branches:
      - main
      - master

jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check CMake version
        run: cmake --version

      - name: Configure (CMake)
        run: cmake ${{ github.workspace }} -B${{ github.workspace }}/build

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test
        run: ctest --test-dir ${{ github.workspace }}/build --output-on-failure


  platformio-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Tests
        run: pio test -vvv

      - name: Test wiring-blink
        run: pio test -d examples/wiring-blink/

      - name: Test mock-injection
        run: pio test -d examples/mock-injection/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: platformio-test-results-${{ matrix.os }}
          path: 
           - .pio/build/native/
           - examples/wiring-blink/.pio/build/native/
           - examples/mock-injection/.pio/build/native/
